package com.mtm.flowcheck.dao.base;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mtm.flowcheck.bean.dao.OrganBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ORGAN_BEAN".
*/
public class OrganBeanDao extends AbstractDao<OrganBean, Void> {

    public static final String TABLENAME = "ORGAN_BEAN";

    /**
     * Properties of entity OrganBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, String.class, "ID", false, "ID");
        public final static Property ORG_NAME = new Property(1, String.class, "ORG_NAME", false, "ORG__NAME");
        public final static Property ORG_CODE = new Property(2, String.class, "ORG_CODE", false, "ORG__CODE");
        public final static Property PID = new Property(3, String.class, "PID", false, "PID");
    }


    public OrganBeanDao(DaoConfig config) {
        super(config);
    }
    
    public OrganBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ORGAN_BEAN\" (" + //
                "\"ID\" TEXT," + // 0: ID
                "\"ORG__NAME\" TEXT," + // 1: ORG_NAME
                "\"ORG__CODE\" TEXT," + // 2: ORG_CODE
                "\"PID\" TEXT);"); // 3: PID
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_ORGAN_BEAN_ID ON \"ORGAN_BEAN\"" +
                " (\"ID\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ORGAN_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OrganBean entity) {
        stmt.clearBindings();
 
        String ID = entity.getID();
        if (ID != null) {
            stmt.bindString(1, ID);
        }
 
        String ORG_NAME = entity.getORG_NAME();
        if (ORG_NAME != null) {
            stmt.bindString(2, ORG_NAME);
        }
 
        String ORG_CODE = entity.getORG_CODE();
        if (ORG_CODE != null) {
            stmt.bindString(3, ORG_CODE);
        }
 
        String PID = entity.getPID();
        if (PID != null) {
            stmt.bindString(4, PID);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OrganBean entity) {
        stmt.clearBindings();
 
        String ID = entity.getID();
        if (ID != null) {
            stmt.bindString(1, ID);
        }
 
        String ORG_NAME = entity.getORG_NAME();
        if (ORG_NAME != null) {
            stmt.bindString(2, ORG_NAME);
        }
 
        String ORG_CODE = entity.getORG_CODE();
        if (ORG_CODE != null) {
            stmt.bindString(3, ORG_CODE);
        }
 
        String PID = entity.getPID();
        if (PID != null) {
            stmt.bindString(4, PID);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public OrganBean readEntity(Cursor cursor, int offset) {
        OrganBean entity = new OrganBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // ID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ORG_NAME
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ORG_CODE
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // PID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OrganBean entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setORG_NAME(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setORG_CODE(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPID(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(OrganBean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(OrganBean entity) {
        return null;
    }

    @Override
    public boolean hasKey(OrganBean entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
